[package]
name = "ggtune"
version = "0.1.0"
authors = ["Lukas Atkinson"]
edition = "2018"

[dependencies]
ndarray = "0.12.1"
ndarray-linalg = { version = "0.11" }
ndarray-stats = "0.2.0"
noisy_float = "0.1.11"  # needed for quantiles
num-traits = "0.2.8"
openblas-src = "0.7.0"
nlopt = "0.5.1"

# the rand crates must share a common rand_core version,
# which prevents us from always using the lastest
rand = "^0.6"
rand_core = "^0.4"
rand_xoshiro = "^0.2"

[dev-dependencies]
speculate = "0.1.2"